import com.petproposal.petproposal.model.Animal;
import com.petproposal.petproposal.dto.UserInfoDto;

global com.petproposal.petproposal.model.Animal animal;
dialect  "mvel"

rule "Check for needed space."
    when
        userInfoDtoInstance:UserInfoDto(animal.spaceNeeded.ordinal <= userSpace.ordinal);
    then
        animal.setResult(animal.getResult() + 1);
end

rule "Check for needed time."
    when
        userInfoDtoInstance:UserInfoDto(animal.timeNeeded.ordinal <= userTime.ordinal);
    then
        animal.setResult(animal.getResult() + 1);
end

rule "Check for potential noise."
    when
        userInfoDtoInstance:UserInfoDto(animal.potentialNoise.ordinal <= bearableNoise.ordinal);
    then
        animal.setResult(animal.getResult() + 1);
end

rule "Check for money needed."
    when
        userInfoDtoInstance:UserInfoDto(animal.moneyNeeded.ordinal <=  moneyForSpendingOnAnimal.ordinal);
    then
        animal.setResult(animal.getResult() + 1);
end

rule "Check for pettable."
    when
        userInfoDtoInstance:UserInfoDto(animal.pettable == animalThatLikesPetting);
    then
        animal.setResult(animal.getResult() + 1);
end

rule "Check for absence from home."
    when
        userInfoDtoInstance:UserInfoDto(animal.absenceFromHome.ordinal <= absentFromHome.ordinal);
    then
        animal.setResult(animal.getResult() + 1);
end

rule "Check for activities."
    when
        userInfoDtoInstance:UserInfoDto(animal.activities == outdoorActivities);
    then
        animal.setResult(animal.getResult() + 1);
end

rule "Check for learning tricks."
    when
        userInfoDtoInstance:UserInfoDto(animal.learningTricks == teachingTricks);
    then
        animal.setResult(animal.getResult() + 1);
end

rule "Check for hair alergy."
    when
        userInfoDtoInstance:UserInfoDto(animal.hairAlergy == true && alergicToHair == true);
    then
        animal.setResult(0L);
end

rule "Check for feather alergy."
    when
        userInfoDtoInstance:UserInfoDto(animal.featherAlergy == true && alergicToFeather == true);
    then
        animal.setResult(0L);
end